#ifndef L_ARM_STRUCT_H
#define L_ARM_STRUCT_H

module subscriber
{
    struct l_arm
    {
        double l_shoulder_pan_joint;
        double l_shoulder_lift_joint;
        double l_upper_arm_roll_joint;
        double l_elbow_flex_joint;
        double l_forearm_roll_joint;
        double l_wrist_flex_joint;
        double l_wrist_roll_joint;
        double time_to_finish;
    };
};
#endif
